---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  vars:
    personal_users:
      - zdufour
      - zanedufour


  tasks:
    - include: tasks/users.yml
    # - name: Install roles
    #   shell: /usr/bin/ansible-galaxy install -p ./roles -r requirements.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
    - include: tasks/python-setup.yml
    - include: tasks/pip.yml
    - include: tasks/node.yml
    - include: tasks/aliases.yml
