---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml

- hosts: localhost
  become_user: "{{ item }}"
  become: true
  roles:
    - role: markosamuli.pyenv
      pyenv_init_shell: true
      pyenv_home: /home/{{ item }}
      pyenv_root: /home/{{ item }}/.pyenv
      pyenv_detect_existing_install: true
      pyenv_python_versions:
        - "3.6.10"
        - "3.7.6"
        - "3.8.1"
      pyenv_global: >-
        3.6.10
        3.7.6
        3.8.1
  loop:
    - zanedufour
    - zdufour

- hosts: localhost
  become_user: zanedufour
  become: true
  tasks:
    - include: tasks/pip.yml
