- name: Install arc theme
  apt: name=arc-theme

- name: create ~/.themes folder
  file:
    path: /home/zanedufour/.themes
    state: directory

- name: create ~/.icons folder
  file:
    path: /home/zanedufour/.icons
    state: directory

- name: Install psutil package
  apt: name=python3-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/zanedufour/.wallpaper.jpg owner=zanedufour group=zanedufour mode=600

- name: Set GNOME wallpaper
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/zanedufour/.wallpaper.jpg'"

- name: Copy lockscreenfile
  become_user: zanedufour
  copy: src=files/lockscreen.jpg dest=/home/zanedufour/.lockscreen.jpg owner=zanedufour group=zanedufour mode=600

- name: Set lock screen background
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/zanedufour/.lockscreen.jpg'"

- name: Set GTK theme
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Pop-dark'"

- name: customize gnome
  include_role:
    name: PeterMosmans.customize-gnome
  vars:
    gnome_user: "{{ user }}"
    gnome_extensions:
      - name: dash-to-dock@micxgx.gmail.com
        url: https://github.com/micheleg/dash-to-dock/archive/ubuntu-dock-68ubuntu1_20.04.1.zip
    gnome_gsettings:
      - schema: org.gnome.desktop.peripherals.touchpad
        key: click-method
        value: areas
    gnome_dconf:
      - key: /org/gnome/shell/extensions/dash-to-dock/show-trash
        value: "false"
  loop:
    - zanedufour
    - zdufour
  loop_control:
    loop_var: user

- name: install dash-to-dock
  become_user: "{{ user }}"
  shell: "wget -c \
    https://github.com/micheleg/dash-to-dock/archive/ubuntu-dock-68ubuntu1_20.04.1.tar.gz \
    -O - \
    | tar -xz -C '/home/{{ user }}/.local/share/gnome-shell/extensions/' \
    "
    # && mv /home/{{ user }}/.local/share/gnome-shell/extensions/dash-to-dock-ubuntu-dock-68ubuntu1_20.04.1/ \
    #   /home/{{ user }}/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/
  args:
    creates: "/home/{{ user }}/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/"
  loop:
    - zanedufour
    - zdufour
  loop_control:
    loop_var: user

- name: Turn on gnome extensions
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "[
      'alt-tab-raise-first-window@system76.com',
      'always-show-workspaces@system76.com',
      'batteryiconfix@kylecorry31.github.io',
      'desktop-icons@csoriano',
      'pop-shell@system76.com',
      'pop-shop-details@system76.com',
      'system76-power@system76.com',
      'ubuntu-appindicators@ubuntu.com',
      'dash-to-dock@micxgx.gmail.com'
      ]"
    state: present
  loop:
    - zanedufour
    - zdufour
  loop_control:
    loop_var: user