- name: Install arc theme
  apt: name=arc-theme

- name: create ~/.themes folder
  file:
    path: /home/zanedufour/.themes
    state: directory

- name: create ~/.icons folder
  file:
    path: /home/zanedufour/.icons
    state: directory

- name: Install psutil package
  apt: name=python3-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/zanedufour/.wallpaper.jpg owner=zanedufour group=zanedufour mode=600

- name: Set GNOME wallpaper
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/zanedufour/.wallpaper.jpg'"

- name: Copy lockscreenfile
  become_user: zanedufour
  copy: src=files/lockscreen.jpg dest=/home/zanedufour/.lockscreen.jpg owner=zanedufour group=zanedufour mode=600

- name: Set lock screen background
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/zanedufour/.lockscreen.jpg'"

- name: Set GTK theme
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Pop-dark'"

- name: customize gnome
  include_role:
    name: PeterMosmans.customize-gnome
  vars:
    gnome_user: "{{ user }}"
    gnome_extensions:
      - name: dash-to-dock@micxgx.gmail.com
        id: 307 # dash-to-dock
        url: https://github.com/micheleg/dash-to-dock/archive/ubuntu-dock-68ubuntu1_20.04.1.zip
    gnome_settings:
      - schema: org.gnome.desktop.peripherals.touchpad
        key: monospace-font-name
        value: areas
  loop:
    - zanedufour
    - zdufour
  loop_control:
    loop_var: user
