- name: install node with nvm
  include_role:
    name: stephdewit.nvm
  vars:
    become: yes
    become_user: "{{ user }}"
    nvm_install: curl
    nvm_dir: "/home/{{ user }}/.nvm"
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user
