- name: install node with nvm
  include_role:
    name: markosamuli.nvm
  vars:
    become: yes
    become_user: "{{ user }}"
    nvm_shell_init: yes
    nvm_shell_profile_scripts:
      - .bashrc
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user
