- name: install nvm
  shell: "
    NVM_DIR=/home/{{ user }} \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  "
  args:
    creates: "/home/{{ user }}/.nvm"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control: 
    loop_var: user

- name: install node with nvm
  command: "
    sudo -iu {{ user }} \
    NODE_VERSION=14 \
    nvm install $NODE_VERSION --default --latest-npm
  "
  # args:
  #   creates: "/home/{{ user }}/.nvm"
  become_user: "{{ user }}"
  # executable: /bin/bash -l
  # sudo_user: "{{ user }} -i"
  loop: "{{ personal_users }}"
  loop_control: 
    loop_var: user
