- name: install nvm
  become_user: "{{ user }}"
  become_flags: "-s /bin/bash"
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash"
  args:
    creates:
      - "/home/{{ user }}/.nvm"
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user
