- name: install nvm
  shell: "
    NVM_DIR=/home/{{ user }} \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  "
  args:
    creates: "/home/{{ user }}/.nvm"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control: 
    loop_var: user

- name: install node with nvm
  shell: bash -ilc "nvm install 12.18.3 --default --latest-npm"
  # sudo_user: "{{ user }} -i"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control: 
    loop_var: user
