- name: install nvm
  shell: "
    NVM_DIR=/home/{{ user }} \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  "
  args:
    creates: "/home/{{ user }}/.nvm"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control: 
    loop_var: user