- apt_repository:
    repo: 'ppa:system76/pop'
    state: present

- name: Install apt packages
  apt:
    name:
      - htop
      - mc
      - tmux
      - gnome-tweaks
      - gnome-shell-extensions
      - pop-theme
      - snapd

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.videolan.VLC
    - com.meetfranz.Franz
    - com.discordapp.Discord
