- apt_repository:
    repo: 'ppa:system76/pop'
    state: present

- name: Install apt packages
  apt:
    name:
      - htop
      - mc
      - tmux
      - gnome-tweaks
      - gnome-shell-extensions
      - pop-theme
      - snapd
    deb:
      - https://discordapp.com/api/download?platform=linux&format=deb

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop:
    - org.videolan.VLC
    - com.meetfranz.Franz

- name: Install snaps
  snap:
    name:
      - discord
     