# based on the docs: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
- name: add brave gpg key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg

- apt_repository:
    repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com stable main"
    state: present
    filename: brave-browser-release

- apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"
    - ppa:system76/pop

- name: Install apt packages
  apt:
    name:
      - dconf-editor
      - fonts-firacode
      - gnome-shell-extensions
      - gnome-tweaks
      - htop
      - libssl-dev
      - mc
      - openconnect
      - pop-theme
      - snapd
      - tmux
      - xclip
      - jq
      - brave-browser
      - brave-keyring
      - thunderbird

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.videolan.VLC
    - com.meetfranz.Franz
    - com.discordapp.Discord

- name: install visual studio code (vscode)
  include_role:
    name: gantsign.visual-studio-code
