- apt_repository:
    repo: 'ppa:system76/pop'
    state: present

- name: Install apt packages
  apt:
    name:
      - htop
      - mc
      - tmux
      - gnome-tweaks
      - gnome-shell-extensions
      - pop-theme

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    loop:
      - org.videolan.VLC
      - com.meetfranz.Franz
    state: present
    method: user

- name: Install snaps
  snap:
    name:
      - discord
     