- apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"
    - ppa:system76/pop

- name: Install apt packages
  apt:
    name:
      - htop
      - mc
      - tmux
      - gnome-tweaks
      - gnome-shell-extensions
      - pop-theme
      - snapd
      - openconnect
      - xclip
      - libssl-dev

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.videolan.VLC
    - com.meetfranz.Franz
    - com.discordapp.Discord
