# based on the docs: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

- name: add keys
  apt_key: "{{ item }}"
  loop:
    - url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
      keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
    - url: https://updates.signal.org/desktop/apt/keys.asc
    - keyserver: keyserver.ubuntu.com
      id: C99B11DEB97541F0
    - url: https://download.docker.com/linux/ubuntu/gpg

- apt_repository:
    repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com stable main"
    state: present
    filename: brave-browser-release

- apt_repository:
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    state: present
    filename: signal-xenial

- apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"
    - ppa:system76/pop
    - "deb https://cli.github.com/packages focal main"
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

- name: Install apt packages
  apt:
    name:
      - apt-transport-https
      - autoconf
      - automake
      - bashtop
      - brave-browser
      - brave-keyring
      - build-essential
      - ca-certificates
      - containerd.io
      - curl
      - dconf-editor
      - docker-ce
      - docker-ce-cli
      - fonts-firacode
      - gh
      - git
      - gnome-shell-extensions
      - gnome-tweaks
      - gnupg-agent
      - htop
      - jq
      - libbz2-dev
      - libffi-dev
      - libgtk-3-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libtomcrypt-dev
      - libtool
      - libxml2-dev
      - llvm
      - mc
      - network-manager-openconnect
      - network-manager-openconnect-gnome
      - openconnect
      - pop-theme
      - python-openssl
      - signal-desktop
      - snapd
      - software-properties-common
      - sqlite3
      - steam-installer
      - sysfsutils
      - thunderbird
      - tk-dev
      - tmux
      - wget
      - xclip
      - xz-utils
      - zlib1g-dev

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.videolan.VLC
    - com.meetfranz.Franz
    - com.discordapp.Discord

- name: install visual studio code (vscode)
  include_role:
    name: gantsign.visual-studio-code

- stat: path=/usr/bin/slack
  register: slack_path

- name: install slack
  include_role:
    name: oefenweb.slack
  when: not slack_path.stat.exists
