- name: install python3.8 libraries
  become_user: zanedufour
  become: true
  pip:
    name: "{{ item }}"
    executable: /home/zanedufour/.pyenv/shims/pip3.8
    extra_args: "--user"
  loop:
    - invoke
    - pipx

# source <(inv --print-completion-script bash)
- name: Set up invoke completion
  become_user: "{{ user }}"
  lineinfile:
    path: "/home/{{ user }}/.bashrc"
    regexp: "source \\<\\(inv --print-completion-script bash\\)"
    line: "source <(inv --print-completion-script bash)"
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user

- name: Install packages with pipx
  become_user: zanedufour
  become: true
  command: "pipx install --python python3.8 {{ item.pkg }}"
  args:
    creates:
      - /home/zanedufour/.local/bin/{{ item.cmd }}
  loop:
    - {"pkg": "black[d]", "cmd": "black"}
    - {"pkg": "pre-commit", "cmd": "pre-commit"}
  loop_control:
    label: "{{ item.pkg }}"
