- name: install python3.8 libraries
  pip:
    name: "{{ item }}"
    executable: /home/zanedufour/.pyenv/shims/pip3.8
    extra_args: "--user"
  loop:
    - invoke
    - pipx

- name: Install packages with pipx
  command: "/usr/bin/env pipx install --python python3.8 {{ item }}"
  args:
    creates:
      - /home/zanedufour/.local/bin/"{{ item }}"
  loop:
    - black[d]
    - pre-commit
