- name: Install slack into {{ user }}
  include_role:
    name: wtanaka.slack
  vars:
    become_user: "{{ user }}"
    become: true
  loop:
    - zanedufour
    - zdufour
  loop_control:
    loop_var: user
